spring.datasource.url=jdbc:postgresql://38.242.201.239:5432/dgifne
spring.datasource.username=postgres
spring.datasource.password=Azerty_@2025
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

server.port=8082
server.address=38.242.201.239
spring.mvc.static-path-pattern=/factures/**
frontend.app.url=http://localhost:4200

file.upload-dir=uploads
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

app.jwt.secret=7A24432646294A404E635266556A586E3272357538782F413F4428472B4B6150
app.jwt.expiration-ms=86400000

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://auth.camandsonsentreprises.com/realms/dgifne-test
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt.auth.converter.resource-id=backend
jwt.auth.converter.principal-attribute=preferred_username

keycloak.admin.host=https://auth.camandsonsentreprises.com
keycloak.admin.realm=dgifne-test
keycloak.admin.clientId=account-management
keycloak.admin.clientSecret=sSgiYxGeMW9VA0mtMdYjWh2NWiCzn7Eb
keycloak.admin.clientUUID=319e48c6-a497-48c6-9c51-34a7f08b4b46

auth.api.url=https://38.242.201.239:9443/oauth2/token

hlh.auth.password=0kBY5f5orhbJUh1o6CeKBBZoCpwa
hlh.auth.user=ejkBr2dGULMDTuqriwl4BEVlC3ga
hlh.api.url=https://38.242.201.239:8243/hlh/api/v1/auth-facture
hlh.api.entreprise=HOTEL AND LUXURY HOUSING

bk.auth.password=jbV0lQRmZtCioWZDuKaeGp72HWga
bk.auth.user=0xqgqqXeZF72uLrQ9BftSOEf778a
bk.api.url=https://38.242.201.239:8243/burger-king/api/v1/auth-facture
bk.api.entreprise=SIA RESTAURATION RAPIDE COTE D'IVOIRE

zino.auth.password=KOf9TXYxY6kaUsz6GalTElFuGeUa
zino.auth.user=S08B5VfGhjhkn_PZJhgYpw84e4ga
zino.api.url=https://38.242.201.239:8243/zino/api/v1/auth-facture
zino.api.entreprise=ZINO COTE D'IVOIRE

cam.auth.password=1j_XGX_V4dwVdT_toue_1_xqbm4a
cam.auth.user=iBx8fO9RDJ7Z5JmyIWpOFHNfWQsa
cam.api.url=https://38.242.201.239:8243/cam/api/v1/auth-facture
cam.api.entreprise=CAM & SONS ENTREPRISES

pagim.auth.password=6C_32mIByAUbAumqWQNp6c_cFbYa
pagim.auth.user=uiH2mNncgK6zQUt7hpjD5Sh5_qMa
pagim.api.url=https://38.242.201.239:8243/pagim/v1/auth-facture
pagim.api.entreprise=PAGIM SERVICES SARL

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aetoumi@gmail.com
spring.mail.password=zximojrrftupyncj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.debug=true

app.environnement=test

server.forward-headers-strategy=framework
server.tomcat.remoteip.remote-ip-header=x-forwarded-for
server.tomcat.remoteip.protocol-header=x-forwarded-proto
server.tomcat.remoteip.host-header=x-forwarded-host

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-metier.sql
spring.sql.init.platform=postgresql
spring.sql.init.continue-on-error=false

spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always

integration.api.telechargement.url=https://38.242.201.239:8243

batch.max-tentatives=3
batch.scheduler.cron=0 */5 * * * ?

app.temp.dir=${java.io.tmpdir}/automatisationzino
app.cleanup.enabled=true

logging.level.com.elpandor.hlh.modules.automatisationzino=DEBUG
logging.level.org.springframework.batch=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

spring.web.client.ssl.verify=false