spring.datasource.url=jdbc:postgresql://38.242.201.239:5432/dgifne
spring.datasource.username=postgres
spring.datasource.password=Azerty_@2025
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


server.port=8082
server.address=38.242.201.239
spring.mvc.static-path-pattern=/factures/**
frontend.app.url=http://localhost:4200

## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
file.upload-dir=uploads
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# JWT
#app.jwt.secret=YourSecretKeyForJWTSigningMustBeAtLeast32BytesLong
app.jwt.secret=7A24432646294A404E635266556A586E3272357538782F413F4428472B4B6150
#24h
app.jwt.expiration-ms=86400000

##Keycloak config
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://auth.camandsonsentreprises.com/realms/dgifne-test
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt.auth.converter.resource-id=backend
jwt.auth.converter.principal-attribute=preferred_username

## keycloak admin settings
keycloak.admin.host=https://auth.camandsonsentreprises.com
keycloak.admin.realm=dgifne-test
keycloak.admin.clientId=account-management
keycloak.admin.clientSecret=sSgiYxGeMW9VA0mtMdYjWh2NWiCzn7Eb
keycloak.admin.clientUUID=319e48c6-a497-48c6-9c51-34a7f08b4b46

# API Manager call API
auth.api.url=https://38.242.201.239:9443/oauth2/token

# HLH Parameter
hlh.auth.password=0kBY5f5orhbJUh1o6CeKBBZoCpwa
hlh.auth.user=ejkBr2dGULMDTuqriwl4BEVlC3ga
hlh.api.url=https://38.242.201.239:8243/hlh/api/v1/auth-facture
hlh.api.entreprise=HOTEL AND LUXURY HOUSING

# Burger King Parameter
bk.auth.password=jbV0lQRmZtCioWZDuKaeGp72HWga
bk.auth.user=0xqgqqXeZF72uLrQ9BftSOEf778a
bk.api.url=https://38.242.201.239:8243/burger-king/api/v1/auth-facture
bk.api.entreprise=SIA RESTAURATION RAPIDE COTE D'IVOIRE

# Burger King Parameter
zino.auth.password=KOf9TXYxY6kaUsz6GalTElFuGeUa
zino.auth.user=S08B5VfGhjhkn_PZJhgYpw84e4ga
zino.api.url=https://38.242.201.239:8243/zino/api/v1/auth-facture
zino.api.entreprise=ZINO COTE D'IVOIRE

# Gestion envoi mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aetoumi@gmail.com
spring.mail.password=zximojrrftupyncj
#spring.mail.properties.mail.store.protocol=pop3
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.debug=true

app.environnement=test

# Forward headers for reverse proxy
server.forward-headers-strategy=framework
server.tomcat.remoteip.remote-ip-header=x-forwarded-for
server.tomcat.remoteip.protocol-header=x-forwarded-proto
server.tomcat.remoteip.host-header=x-forwarded-host