#spring.datasource.url=jdbc:postgresql://localhost:5432/hlhdgi
spring.datasource.url=jdbc:postgresql://localhost:5432/fneprod
spring.datasource.username=postgres
spring.datasource.password=Azerty@2024
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


server.port=8082
server.address=localhost
spring.mvc.static-path-pattern=/factures/**
frontend.app.url=http://localhost:4200

## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
file.upload-dir=uploads
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Tesseract OCR Configuration
# Windows: C:\Program Files\Tesseract-OCR\tessdata
# Linux: /usr/share/tesseract-ocr/4.00/tessdata
tesseract.datapath=C:\\Program Files (x86)\\Tesseract-OCR\\tessdata
tesseract.language=fra+eng

# Logging
logging.level.org.springframework=INFO
logging.level.com.example=DEBUG

# JWT
#app.jwt.secret=YourSecretKeyForJWTSigningMustBeAtLeast32BytesLong
app.jwt.secret=7A24432646294A404E635266556A586E3272357538782F413F4428472B4B6150
#24h
app.jwt.expiration-ms=86400000

##Keycloak config
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090/realms/dgifne
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt.auth.converter.resource-id=backend
jwt.auth.converter.principal-attribute=preferred_username

## keycloak admin settings
keycloak.admin.host=http://localhost:8090
keycloak.admin.realm=dgifne
keycloak.admin.clientId=account-management
keycloak.admin.clientSecret=6VB2o1EyUH6UzwWPZLkqmNfKXy9oSRNh
keycloak.admin.clientUUID=f62ea3e9-10ae-4531-a604-ce700eabea0e

# API Manager call API
auth.api.url=https://localhost:9443/oauth2/token

# HLH Parameter
hlh.auth.password=_4X8iy3vqYafxdgsQFewTr8Gy7Ma
hlh.auth.user=9N8Vf57KfjeGrR1SZ2LIVjt1POwa
hlh.api.url=https://localhost:8243/hlh/api/v1/auth-facture
hlh.api.entreprise=HOTEL AND LUXURY HOUSING

# Burger King Parameter
bk.auth.password=jHAaASc1GNoPTJnjFgO3wfZCMRUa
bk.auth.user=RV5EgkeVrk_fMUEjlJKGTsflomka
bk.api.url=https://localhost:8243/burger-king/api/v1/auth-facture
bk.api.entreprise=SIA RESTAURATION RAPIDE COTE D'IVOIRE

# ZINO Parameter
zino.auth.password=Dt_XBNcBChJpGUyEmR7TtXOdxUMa
zino.auth.user=XuXrjgjAVeNcgZxQLz6MivCVnZYa
zino.api.url=https://localhost:8243/zino/api/v1/auth-facture
zino.automatisation-liste-file.api.url=https://localhost:8243/zino/api/v1/automatisation/list-files
zino.automatisation-download-file.api.url=https://localhost:8243/zino/api/v1/automatisation/{filename}/download
zino.api.entreprise=ZINO COTE D'IVOIRE

# CAM & SONS Parameter
cam.auth.password=RKsImFsLCpBCh7Ny9W98tXpxSLsa
cam.auth.user=BG5XsAFn4uTyROUGiylLwIy93C0a
cam.api.url=https://localhost:8243/cam/api/v1/auth-facture
cam.api.entreprise=CAM & SONS ENTREPRISES

# PAGIM Parameter
pagim.auth.password=InB9Dy4eR5_t4rKLQ5lMflSHrvUa
pagim.auth.user=E4ZHiQ3SalhQoEy6Wgcm6DzwuQEa
pagim.api.url=https://localhost:8243/pagim/v1/auth-facture
pagim.api.entreprise=PAGIM SERVICES SARL

# Gestion envoi mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aetoumi@gmail.com
spring.mail.password=bbbtqyemxojnffdn
#spring.mail.properties.mail.store.protocol=pop3
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.debug=true

app.environnement=developpement

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-metier.sql
spring.sql.init.platform=postgresql
spring.sql.init.continue-on-error=false

spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=always

integration.api.telechargement.url=https://localhost:8243

batch.max-tentatives=3
batch.scheduler.cron=0 */5 * * * ?

app.temp.dir=${java.io.tmpdir}/automatisationzino
app.cleanup.enabled=true

logging.level.com.elpandor.hlh.modules.automatisationzino=DEBUG
logging.level.org.springframework.batch=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

spring.web.client.ssl.verify=false
