spring.datasource.url=jdbc:postgresql://62.171.143.224:5432/dgifne
spring.datasource.username=postgres
spring.datasource.password=Azerty_@2025
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


server.port=8082
server.address=62.171.143.224
spring.mvc.static-path-pattern=/factures/**
frontend.app.url=https://app.camandsonsentreprises.com

## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
file.upload-dir=uploads
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# JWT
#app.jwt.secret=YourSecretKeyForJWTSigningMustBeAtLeast32BytesLong
app.jwt.secret=7A24432646294A404E635266556A586E3272357538782F413F4428472B4B6150
#24h
app.jwt.expiration-ms=86400000

##Keycloak config
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://auth.camandsonsentreprises.com/realms/dgifne
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt.auth.converter.resource-id=backend
jwt.auth.converter.principal-attribute=preferred_username

## keycloak admin settings
keycloak.admin.host=https://auth.camandsonsentreprises.com
keycloak.admin.realm=dgifne
keycloak.admin.clientId=account-management
keycloak.admin.clientSecret=LdOdAXcEnnIwuwXTd3DOoPHiYbbHSvtV
keycloak.admin.clientUUID=f62ea3e9-10ae-4531-a604-ce700eabea0e

# API Manager call API
auth.api.url=https://62.171.143.224:9443/oauth2/token

# HLH Parameter
hlh.auth.password=CWxMAnNLNlNXcg4E71FZlf5jx7sa
hlh.auth.user=RNYSgVnZYDKldxWhCMnm6E6uFCga
hlh.api.url=https://62.171.143.224:8243/hlh/api/v1/auth-facture
hlh.api.entreprise=HOTEL AND LUXURY HOUSING

# Burger King Parameter
bk.auth.password=6mbY5DaZiIPMidwqQVL4N4QUMpIa
bk.auth.user=_TVMESifThztp5fHcJ_0PfP1lkUa
bk.api.url=https://62.171.143.224:8243/burger-king/api/v1/auth-facture
bk.api.entreprise=SIA RESTAURATION RAPIDE COTE D'IVOIRE

# Burger King Parameter
zino.auth.password=6mbY5DaZiIPMidwqQVL4
zino.auth.user=_TVMESifThztp5fHcJ_0
zino.api.url=https://62.171.143.224:8243/zino/api/v1/auth-facture
zino.api.entreprise=ZINO COTE D'IVOIRE

# Gestion envoi mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aetoumi@gmail.com
spring.mail.password=zximojrrftupyncj
#spring.mail.properties.mail.store.protocol=pop3
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.debug=true

app.environnement=production

# Forward headers for reverse proxy
server.forward-headers-strategy=framework
server.tomcat.remoteip.remote-ip-header=x-forwarded-for
server.tomcat.remoteip.protocol-header=x-forwarded-proto
server.tomcat.remoteip.host-header=x-forwarded-host