spring.datasource.url=jdbc:postgresql://localhost:5432/hlhdgi
spring.datasource.username=postgres
spring.datasource.password=Azerty@2024
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


server.port=8082
server.address=localhost
spring.mvc.static-path-pattern=/factures/**
frontend.app.url=http://localhost:4200

## File Storage Properties
# All files uploaded through the REST API will be stored in this directory
file.upload-dir=uploads
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# JWT
#app.jwt.secret=YourSecretKeyForJWTSigningMustBeAtLeast32BytesLong
app.jwt.secret=7A24432646294A404E635266556A586E3272357538782F413F4428472B4B6150
#24h
app.jwt.expiration-ms=86400000

##Keycloak config
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8090/realms/dgifne
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt.auth.converter.resource-id=backend
jwt.auth.converter.principal-attribute=preferred_username

## keycloak admin settings
keycloak.admin.host=http://localhost:8090
keycloak.admin.realm=dgifne
keycloak.admin.clientId=account-management
keycloak.admin.clientSecret=6VB2o1EyUH6UzwWPZLkqmNfKXy9oSRNh
keycloak.admin.clientUUID=f62ea3e9-10ae-4531-a604-ce700eabea0e

# API Manager call API
auth.api.url=https://localhost:9443/oauth2/token

# HLH Parameter
hlh.auth.password=dlp_wlrG5UmnetErBMlxFB0N2NIa
hlh.auth.user=5jkwhQiOiz13tCdQPQClIDTHdewa
hlh.api.url=https://localhost:8243/hal-api/v1/auth-facture

# Gestion envoi mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aetoumi@gmail.com
spring.mail.password=zximojrrftupyncj
#spring.mail.properties.mail.store.protocol=pop3
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.debug=true

app.environnement=developpement